### ISSUE TITLE
scrolling up not loading the data

### ISSUE THREAD

**Issue by eliorcohen** [aurelia/ui-virtualization#1]
Hi, 

looking at the demo in chrome browser, when adding 1000, the scroll down work perfectly, but when scrolling up, the rows are not loaded and the view is empty..

**Comment by martingust** [comment]
I'm not able to reproduce this, using Chrome v43.0.2. Is this happening on first load? Or when you first add/remove items or resize the container?

**Comment by eliorcohen** [comment]
i have tried to reproduced it again with no success..

**Comment by martingust** [comment]
ok, thanks for checking. I'll keep this open for a little bit if it crops up again.

**Comment by EisenbergEffect** [comment]
I'm going to close this for now until we see the behavior happen again and can find a way to reproduce it.
