### ISSUE TITLE
Add support for PageUp, PageDown, Home, and End keys

### ISSUE THREAD

**Issue by jwahyoung** [aurelia/ui-virtualization#10]
The plugin supports scrolling by keyboard but does not capture non-arrow keypresses. Quick fix for this is as follows in `scrollHandler.js`:

```
  keyDown(event) {
    var delta = 0;
    switch(event.keyCode) {
      case 36: // Home key
        delta = Number.POSITIVE_INFINITY;
        break;
      case 35: // End key
        delta = Number.NEGATIVE_INFINITY;
        break;
      case 33: // Page up
        delta = this.pageStep;
        break;
      case 34: // Page down
        delta = -this.pageStep;
        break;
      case 38: // Up arrow
        delta = this.keyStep;
        break;
      case 40: // Down arrow
        delta = -this.keyStep;
        break;
    }
```

**Comment by rquast** [comment]
Thanks, Jedd. That works for me.

I used the code in my fork plus I added a onmouseover="focus()" for the template so it gets the key events when a mouse is hovered over it, without having to click on it first.

For the key and page steps, maybe there's some way we can measure the rendered height of the custom element and use that instead of a magic number? That way page down will be a page, and not skip pages.

**Comment by jwahyoung** [comment]
@rquast Indeed. I actually mentioned this in the comments section of https://github.com/aurelia/ui-virtualization/pull/12. At first I thought the height would have to be passed to the scrollhandler `initialize` function, but it looks like the first argument to that is a DOM element, so it might actually be possible to grab the height from that and use that as the page length. Offhand, I'm not sure how to handle the container resizing. There's an event for that in `virtual-repeat.js` but I haven't yet looked deeply into changing the page scroll height.

Edit: Whoops, accidentally clicked "Close" instead of "Comment".

**Comment by jedd-ahyoung** [comment]
https://github.com/jedd-ahyoung

**Comment by rquast** [comment]
virtual-repeat contains an updated scroll container height. I've passed it in, but I think I need to work on the delta (it doesn't do a full page down even though it sends container height).

https://github.com/rquast/ui-virtualization/commit/92b5e2d51067c6b88e4bc446777137d38abd37af

**Comment by jedd-ahyoung** [comment]
Roland:

Just touching base. I was supposed to get in contact with you on Thursday
via Skype - I unfortunately had something come up which forced me to alter
that plan. However, I'm still interested in seeing your spec and providing
an estimate for you.

If you're still interested, let me know. I haven't been as active on Gitter
lately as I was before, but I can be reached through Gitter (it'll notify
me), through Gmail, or through Google Hangouts (using my email address,
jedd.ahyoung@gmail.com) via text or video chat. I can also be reached on
Skype at username lunchmeat317.

Hope to hear from you.

Jedd Ahyoung
jedd.ahyoung@gmail.com

**Comment by martingust** [comment]
@rquast @jedd-ahyoung Wow I'm glad to see the activity and work you guys putting into the plugin. Will go over the PRs soon, thanks!
