### ISSUE TITLE
infinite scroll on an empty array

### ISSUE THREAD

**Issue by alexisargyris** [aurelia/ui-virtualization#102]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.3.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
Chrome 57

* **Language:**
TypeScript 2.2.0

**Current behavior:**

infinite scroll on an empty array just displays the (empty) parent container

**Expected/desired behavior:**

call the function passed to 'infinite-scroll-next'

* **What is the motivation / use case for changing the behavior?**

start automatically to populate the array

**Comment by amartens181** [comment]
Is this fixed in 6f92c31?

**Comment by bigopon** [comment]
The commit fixed issues related to collection mutation and collection assignment. I don't think it fixes this issue by any chance. Not sure how it's gonna be working, as `infinite-scroll-next` is supposed to be used for fetching next items, not part of the initialization ?

**Comment by Alexander-Taran** [comment]
Yeah.. "holding it wrong"
but I remember there was another issue related to this.. where w/o scroll available fetch-next would not fire.. and use case was to get enough items for scroll to appear.. but what if it's too much..
ppl seem to want to get the exact amount of items..

**Comment by bigopon** [comment]
@alexisargyris @amartens181 the PR at #142 should also fix this issue. Thank you for reporting this bug ❤️ 

Demo app at https://dist-lvubilwhjh.now.sh/#/issue-102
Optionally you can also check out and rebuild the sample app:

```shell
cd sample/sample-v-ui-app
npm install
npm run dev
# go to http://localhost:8080/#/issue-102
```
