### ISSUE TITLE
Methods in Attached() and Bind() are not being called for every item in an array

### ISSUE THREAD

**Issue by bdacoderchris** [aurelia/ui-virtualization#108]
**I'm submitting a bug report**

**-Library Version:**
1.0.0-beta.3.0.2

**-Please tell us about your environment:**

**-Operating System:**
Windows 10

**-Node Version:**
6.9.2

**-NPM Version:**
3.10.9

**-Browser:**
all

**-Language:**
all

**Current behavior:**
Using the virtualization library, `bind()` and `attached()` are not being called for all of my custom elements, just some. For example: In my list of 500 items, only the top 100 would have their bind/attached method called. 

**-Expected/desired behavior:**
The expected behavior would be for the `attached()` and `bind()` methods to be called for each item in the list as you scroll up or down.

I tried to create a Gist, but I was not able to add the Aurelia-UI-Virtualization library to the Gist in order to demonstrate the behavior.

Here is a link to my repo containing the example of the behavior:
https://github.com/bdacoderchris/Aurelia-Ui-Virtualization-Test

**Comment by vegarringdal** [comment]
Isnt it best if it just do bind/attached events when it creates the actual rows, doing unbind/detached, bind and attached when scrolling would prb use a lot more resources, then just setting new value to the bindingContext ?

In the new grid Im making Im just doing setting new values, maybe that is not good? hmm
https://vegarringdal.github.io/vGridDemo/

**Comment by bigopon** [comment]
I think ideally bind should be called for all items, but attached detached will be called depending on the situation. @EisenbergEffect can you revise this to see if it's actually a bug or design decision ?

**Comment by avrahamcool** [comment]
In my opinion:
one can have the ability to replace "repeat.for" with "virtual-repeat.for" and back without major changes in the behavior of the components themselves.
the only difference should be in the behavior of the container and the scroll etc..

if this point of view is correct:
we should always call `attached` on all elements, even if they are not currently loaded into view.
and `detached` should be called only when an item really stop to exist.
(if it was removed from the array, or if we navigated away competently etc..)
but not when we scroll away and back.. just like the normal behavior of a regular `repeat`.

with that being said, we could still benefit from a new event (or life cycle hook) - suited for the `virtual.repeat` that will fire when the item is loaded into view, and another one when the item exits the view.
we can have a parameter that indicates if it's the first time this item becomes visible, or if it's already been loaded before and now we are just returning back to it.. and maybe more details that make sense.

we can argue if this "new" lyfecycle hook should really be a new one, or should it just be `attached` and `detached`.
or maybe it should not even be a lyfecycle hook on the item being repeated - but rather an event that the wrapper emit..

any one of those option can be good as long as they are correctly documented.

lastly: thanks a lot for this great plugin (saved me a ton of time and energy)

**Comment by bigopon** [comment]
@EisenbergEffect @bdacoderchris @avrahamcool On a second thought, doing this would be against the idea of virtualization: only necessary part will be rendered.

@vegarringdal Are you saying there is a way to handle this case?

**Comment by vegarringdal** [comment]
@bigopon

I did not do bind /attached/detached more then once it in my grid. (v-grid)
Doing that might trigger more js work then needed. Components usually have binables to handle data/value change.
But I think not unbinding/binding will use a lot more memory if its a large collection. Since there will be listeners on each array element.
Noticed this when using grid(rebuild) in mframejs, started to experiment with proxies to keep memory usage low.

**Comment by bigopon** [comment]
@bdacoderchris @avrahamcool  Thanks for filing this issue, but I think this is a won't fix, since it violates virtualization principles. Please feel free to reopen if you feel otherwise.
