### ISSUE TITLE
Please rebuild the dist after fixing breaking changes.

### ISSUE THREAD

**Issue by rquast** [aurelia/ui-virtualization#11]
I can't get this to work with the latest Aurelia because the dist was last updated 3 months ago. If fixing a breaking change, could you please make it part of the workflow to also update the dist? Thanks! :)

Currently broken is aurelia.globalizeResources in index.js.

**Comment by rquast** [comment]
Duplicate: https://github.com/aurelia/ui-virtualization/issues/9

**Comment by EisenbergEffect** [comment]
We will get this into our standard release sequence soon. Hang in there!

**Comment by rquast** [comment]
It's all good. I'll just fork things that need fixing for now until they're ready.
