### ISSUE TITLE
With.bind not working with ui-virtualization?

### ISSUE THREAD

**Issue by JordyvA** [aurelia/ui-virtualization#110]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre
1.0.0-beta.3.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Chrome 59.X

* **Language:**
all

**Current behavior:**
I've got the error "element.getBoundingClientRect is not a function". I think the "element" is a comment element because of the Aurelia comment-tags. I've figured out that the issue only exists when I'm using "with.bind" binding. When I get rid of that, everything works fine. I've made the following codesandbox:
https://codesandbox.io/s/4xwP3NEQn

**Expected/desired behavior:**
List should work

* **What is the expected behavior?**
List should work

* **What is the motivation / use case for changing the behavior?**
Then it's working again with bindings as well.

**Comment by bigopon** [comment]
@JordyvA Adding `with.bind` on the same element with `virtual-repeat.for` will make the repeat unable to acquire the root element of each view. Simple nest `with.bind` in a `<template>` directly under repeated element will solve this issue.

```html
<template>
  <h1>${message}</h1>
  <div virtual-repeat.for="person of persons">
    <template with.bind="person">
      ${Name}
    </template>
  </div>
</template>
```

Sandbox at: https://codesandbox.io/s/mm82n6o8pj
