### ISSUE TITLE
Bottom placeholder height not updated when getter changed with computedFrom

### ISSUE THREAD

**Issue by fragsalat** [aurelia/ui-virtualization#114]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.1.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 17.10

* **Node Version:**
8.4.0

* **NPM Version:**
5.3.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
virtual-repeat has to iterate over the return value of a getter annotated with computedFrom. The source objects changes and the getter evaluates new which results in a new array instance which get's bound to the custom attribute.

**Expected/desired behavior:**
When the attribute gets a new array instance from outside it should update the placeholder heights.

**How to fix:**
Currently the ArrayRepeatStrategy.itemsChanged is called on attached lifecycle instead of the bind: https://github.com/aurelia/ui-virtualization/blob/master/src/virtual-repeat.js#L90
Actually it has to be called on both (attached and bind) since bind will be called before the element is attached and you can calculate the height only when it's attached. But bind can be called after attachment as well :)
You could easily optimize the the initial redundancy by check if the element already is attached.
As well the check in the calculation has to be extended that it permits the case when views are there but no items
https://github.com/aurelia/ui-virtualization/blob/master/src/virtual-repeat.js#L457

Previous
```js
if (this._viewsLength > 0 && this._itemsLength === itemsLength || itemsLength <= 0) {
  return;
}
```

After
```js
if (this._viewsLength > 0 && this._itemsLength === itemsLength || this._viewsLength <= 0 && itemsLength <= 0) {
  return;
}
```

**Comment by fragsalat** [comment]
During updating the tests I recognized that the problem only occurs when a huge item list is changes to an empty one.

**Comment by Alexander-Taran** [comment]
PR merged
seems like it can be closed
