### ISSUE TITLE
Unshifting items onto array isn't seemless

### ISSUE THREAD

**Issue by allencoded** [aurelia/ui-virtualization#117]
With the virtualization I have loaded in 20 items from an array. As the user scrolls down I load in 20 more items and it works perfectly. However as the user begins to scroll up I attempt to unshift onto the array of items adding 20 more to the top of the array. 

However while 20 more shift into the top of the array it pushes all the others down. In other words it doesn't seem to hold my place and seamlessly pushes 20 more onto the top.
---------------▲
[Item 21]
[Item 22]
[Item 23]
---------------▼

Now I scroll down and push more on top of that
------------------▲
[Item 1]
[Item 2]
[Item 3]
------------------▼

It just shoves them all on top but doesn't hold my place so I loose track of the items I was just looking at.

Using the latest virtualization.

**Comment by Alexander-Taran** [comment]
there is infinite-scroll-next, but i don't see infinite-scroll-previous.
You might want to rethink your strategy or change this issue to a feature request.
But it would be great if you could provide a Pull Request
https://github.com/aurelia/ui-virtualization

**Comment by Alexander-Taran** [comment]
maybe can be closed.

**Comment by ciriousjoker** [comment]
Same issue here.. This one and 8 of the other bugs just make this completely unusable for me.

Is this even updated anymore?

I mean, the latest commit is from 10 days ago, but there are still bugs from 2016/2017 :(

**Comment by bigopon** [comment]
For normal unshifting item to an array/collection:
This behavior can sometimes come from how scroll position is kept, natively implemented by browser. If scroll position is topmost, inserting any element to the scroller will result in unchanged scroll position, which we quite did a right thing there.
For infinite scroll next:
To have the behavior of "pushing down" with infinite scroll next, there needs to be a way to have offset, so repeat doesn't wait until scroll position hits top.

**Comment by bigopon** [comment]
the pr at #154 solves this issue by mimicking the behavior of normal DOM mutations: visible items in scroller view port are kept visible if something happens before the visible items that either pushes them down or pulls them up.

Note that it cannot have this behavior when used with a value converter in repeat expression. It's a limitation, at least for now, that value converter will make mutation treated as items changed, instead of a mutation.
