### ISSUE TITLE
Cannot read property 'lastChild' of undefined - error when data loads empty

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/ui-virtualization#119]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.1.2
(works well for 1.0.0-beta.3.1.1 and below)

**Current behavior:**
![error](https://user-images.githubusercontent.com/5445320/33680542-a1b8b19c-daca-11e7-8017-6a1b28172540.png)

if the data is empty when the view loads, the virtual-repeat throws an error.
already discussed on the commit itself - but I opened an issue so it would be easier to track.

https://github.com/aurelia/ui-virtualization/commit/0e0b702

**Comment by JordyvA** [comment]
Same issue over here, have picked 1.0.0-beta.3.1.1 for now.

**Comment by bigopon** [comment]
@EisenbergEffect @AStoker this PR #105  that adds support for `null/ undefined` also tackles this issue. Would be great if you can review and merge it so folks can continue with their work. Having null/ undefined / empty array support making it a lot easier / more Aurelia.

**Comment by EisenbergEffect** [comment]
Deferring to @AStoker

**Comment by avrahamcool** [comment]
any news on this?

**Comment by avrahamcool** [comment]
should be fix by: https://github.com/aurelia/ui-virtualization/pull/127
