### ISSUE TITLE
Scrolling up/down with table and virtual-repeat-for causes display bugs

### ISSUE THREAD

**Issue by reft** [aurelia/ui-virtualization#128]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **Browser:**
Chrome

* **Language:**
TypeScript >=1.9.0-dev || ^2.0.0

**Current behavior:**
Using table with virtual-repeat-for is causing unexpected bugs with the display of the array.

It seems like the order of the array is changed, for example if I have fifty rows with ids 1-50 and then scroll up and down the order of which the array is displayed is changed. Instead of the first row being id=1 it's something else depending on how you scrolled.

**Expected/desired behavior:**
Should display array in proper order.

**What is the motivation / use case for changing the behavior?**
In it's current state it's not viable to use table with aurelia virtualization.

Repo with example:
[https://github.com/reft/au-virtualization-table](https://github.com/reft/au-virtualization-table)

Before scrolling up and down:

![1](https://user-images.githubusercontent.com/3218213/36063172-a956c744-0e79-11e8-9b8a-981b72b882f5.png)

After scrolling up and down:

![2](https://user-images.githubusercontent.com/3218213/36063173-af242c02-0e79-11e8-8e62-60a0bd2cf083.png)

As you can see the first row has switched position with another element in the array. In my case id 1 has swapped position with id 38. The problem seems to only affect the first element in the array but I'm not 100% sure.

Please clone the provided repo to reproduce the bug.

**Comment by veikkoeeva** [comment]
Might be related to https://github.com/aurelia/ui-virtualization/pull/101 too.

**Comment by tbnovaes** [comment]
I'm having same problem, with components. I'm creating a table, and each row has 3 charts, when I scroll up and down, the attached/detached method of the component is not called again. So it loads the wrong component.

It would also be nice to have rowCreated and scrollingStarted, scrollingEnded callbacks.

**Comment by phanithinks** [comment]
any update on this. I am too facing same problem. Is there any work around for this

**Comment by avrahamcool** [comment]
same issue here..

**Comment by bigopon** [comment]
I'll take a look

**Comment by bigopon** [comment]
@reft @avrahamcool @PhanindraKumar A fix is at #131, could you guys give it a check ?

**Comment by phanithinks** [comment]
@bigopon I can still see the issue. One thing may be its because we are not using html table. we are using div with flex box to build tables. does it make any difference ?
