### ISSUE TITLE
Prevent parent elements from scrolling on custom element scroll.

### ISSUE THREAD

**Issue by rquast** [aurelia/ui-virtualization#13]
The current implementation using requestAnimationFrame() => this.scroll() does not factor in the parent frame scrolling. Maybe use something like onmouseover / onmouseout on the custom element to disable parent scrolling? Will have a look at different ways.

**Comment by rquast** [comment]
Found the bug in scroll-handler.js... mouseWheel(event) and wheel(event) don't have the following at the end:

event.preventDefault();
event.stopPropagation();
return false;

**Comment by jwahyoung** [comment]
While this works well (and actually fixes some issues with small lists), it may be better to attempt to handle this as a native element would - if the element cannot scroll any farther, the event would then propagate to parent elements.

**Comment by rquast** [comment]
Good point!

**Comment by rquast** [comment]
```
if (this.offset != this.lastOffset) {
  this.lastOffset = this.offset;
  event.preventDefault();
  event.stopPropagation();
  return false;
} else {
  this.lastOffset = this.offset;
}
```

??

**Comment by martingust** [comment]
Closing this since scroll events and scroll-handler.js is not used anymore.
