### ISSUE TITLE
Add rowCreated, scrollStarted and scrollEnded callbacks

### ISSUE THREAD

**Issue by tbnovaes** [aurelia/ui-virtualization#130]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.3.2.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.3

* **Node Version:**
9.4.0

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Right now the only callback we have it the infinite-scroll

**Expected/desired behavior:**
It would be great to have rowCreated, scrollStarted and scrollEnded callbacks

* **What is the expected behavior?**
Having extra hooks called, so it can offer more control of how to load/display the data.

* **What is the motivation / use case for changing the behavior?**
If you have http requests being done, it would be great to be able cancel them once the scroll starts and just query the data for the new rows once the scroll finishes.

**Comment by avrahamcool** [comment]
this will be really helpful.

**Comment by bigopon** [comment]
For `rowCreated`, I'm not sure if it will be useful, as most of the time, it's the same old row that got shifted around. For `scrollStart` and `scrollEnd`, I'm not sure how it's different with normal scroll event?

cc @EisenbergEffect @AStoker about `rowCreated`

**Comment by EisenbergEffect** [comment]
It looks like the original request by @tbnovaes was about loading data, which I think is now handled. I'll close this for now. We can re-open if we discover that those hooks are not sufficient.
