### ISSUE TITLE
preserve scroll position after sorting a long list

### ISSUE THREAD

**Issue by alexisargyris** [aurelia/ui-virtualization#133]
Hello,

If the user is at the top of a really long list and reverses the list's sorting the current item is now at the bottom. Given that scrolling to the new position is not feasible or even desirable how such a situation should be handled?

**Comment by bigopon** [comment]
@alexisargyris Can you elaborate your scenario a bit? Do you want to scroll to bottom where the old item is supposed to be, or you want to keep the scroll at where it is?
