### ISSUE TITLE
Empty item at the top of list

### ISSUE THREAD

**Issue by petronellius** [aurelia/ui-virtualization#134]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.4

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Tested on Chrome 68.0.3440.106

* **Language:**
TypeScript 2.8.1

**Current behavior:**
When CPU is high and new items are added to the list and then list is quickly scrolled to the top, empty list item appears.
![image](https://user-images.githubusercontent.com/12825401/44904100-7cd0b480-ad0e-11e8-814f-ea956986cc25.png)

**Steps to reproduce:**

1. Open [plunker](https://plnkr.co/edit/KdyzXzGvuKljabgR2Gnh?p=preview) in Chrome
2. Open DevTools and in Performance tab set CPU throttling to be 6x slowdown
3. In plunker click "Add items..." button
4. Scroll down in list, click "Load more items..." and press 2x Home key on keyboard.

When I remove progress indicator the issue disappears. Not sure if the reason is that its animation causes the CPU be higher or if it is somehow in collision with virtual-repeat.for.

**Comment by bigopon** [comment]
I can't seem to be able to reproduce this with latest commit. Sample app at https://dist-qdzaosxjeb.now.sh/#/ @petronellius Can you help test this?

@EisenbergEffect Can be closed.
