### ISSUE TITLE
content projection causes missing buffer elements

### ISSUE THREAD

**Issue by tmueller** [aurelia/ui-virtualization#136]
_Originally posted by @martingust in https://github.com/aurelia/ui-virtualization/issues/45#issuecomment-228839089_

>@Thanood I located and resolved #68 but indeed it was not the same issue. There is a problem to insert the buffer elements in conjunction with content projection - right now it tries to insert the buffer elements before `au-content` element which is not in the DOM at the time and the buffer end up not being added to the DOM. Will need to look more into this.

When using content projection, the buffer elements are appended to an `<au-content>` element while the virtual repeats created children are appended to the custom element in the dom.

**Comment by bigopon** [comment]
A workaround would be nesting the repeated element inside projected content. I'm not sure about the effort to support this. Note that with native ShadowDOM, it should be very simple to do.

**Comment by tmueller** [comment]
Thanks for the answer, @bigopon. 
Using ShadowDOM is no possible in this project, we have to support IE11 🙄 
Unfortunately I don't quite understand what your suggested workaround would look like. Could you be so kind to provide an example?

**Comment by bigopon** [comment]
@tmueller I was suggesting this:

Change from:
```html
<my-el>
  <div virtual-repeat></div>
</my-el>
```
to:
```html
<my-el>
  <div>
    <div virtual-repeat></div>
  </div>
</my-el>
```

What we want to do is to avoid having virtually repeated element direct child of a custom element

**Comment by tmueller** [comment]
I see. The buffer elements are attached to the div, which is attached to the DOM afterwards. Should work, thanks :)

**Comment by bigopon** [comment]
This is workaround-able, also probably won't be easily fixed so I'll close this to prioritize on other items. Please feel free to reopen if you find any argument against this.
