### ISSUE TITLE
aurelia-ui-virtualization cannot be used in CodeSandbox

### ISSUE THREAD

**Issue by Sayan751** [aurelia/ui-virtualization#137]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.3.2

**Please tell us about your environment:**
* **Environment**
CodeSandbox

* **Operating System:**
NA

* **Node Version:**
NA

* **NPM Version:**
NA

* **JSPM OR Webpack AND Version**
NA (most probably Webpack)

* **Browser:**
Chrome 71.x | Firefox 63.x 

* **Language:**
ESNext

**Current behavior:**
Unable to use "aurelia-ui-virtualization" package in CodeSandbox. Getting following error:

> DependencyNotFoundError: Could not find dependency: 'src' relative to '/codesandbox.js'

Link to Sandbox: https://codesandbox.io/s/1wq959mk34

**Expected/desired behavior:**

* **What is the expected behavior?**
The "aurelia-ui-virtualization" package should have been available for use after adding the package to dependencies.

* **What is the motivation / use case for changing the behavior?**
Example involving aurelia-ui-virtualization can be created and shared easily.

**Comment by bigopon** [comment]
@Sayan751 Thanks. This can probably be fixed by migrating this plugin to a single file output build. @EisenbergEffect Should we do it for this plugin?

**Comment by EisenbergEffect** [comment]
@bigopon That seems like a good idea if you are up for it.

**Comment by EisenbergEffect** [comment]
This will be addressed in the next release, coming soon. Fixes are merged.
