### ISSUE TITLE
Turn scroll indicator into a draggable bar.

### ISSUE THREAD

**Issue by rquast** [aurelia/ui-virtualization#14]
I don't know what the default is for mobile apps, but a desktop app needs a scroll bar rather than the indicator div.

**Comment by rquast** [comment]
I was looking at gitter's scrollbar and they use webkit scrollbars: https://css-tricks.com/examples/WebKitScrollbars/

Would this be a better solution?

**Comment by martingust** [comment]
I think that is a good idea. It could detect device and based on display different scrollbars.

**Comment by jwahyoung** [comment]
Note that the webkit scrollbar is actually a native scrollbar - so as far as I know (from the limited research I did) we wouldn't be able to control the height and scroll position of the element. Gitter does use this, but they don't have a true virtual scroll - they append to their chat list when the scroll hits the bottom or top (meaning that the scrollbar jumps).

We may be able to emulate a scrollbar that we can control, and have it show up as a scrollbar for assistive technologies (using the WAI-ARIA role).

**Comment by martingust** [comment]
@jedd-ahyoung Correct. We can't use a native scrollbar. Maybe do something similar to the scrollbar on OS X which is just an mobile like indicator and on mouseover turn it to a more draggable friendly style and handle dragging.

**Comment by EisenbergEffect** [comment]
We might want to get @joelcoxokc involved in this too. He's working on Aurelia interface and may have some feedback on how to handle emulating the scroll bars.

**Comment by rquast** [comment]
@martingust @EisenbergEffect What about just making the scrollbar a pluggable component? This way we're not relying on someone else's implementation. I would imagine this project would get forked a few times if it wasn't extendible... same could be said for any component that has sub-components.

@jedd-ahyoung I'd very much like to see any component implement WAI-ARIA properly. Even some kind of validation process for aurelia components to meet that and other standards would be good.

**Comment by jwahyoung** [comment]
@rquast I'd definitely like to push for accessbility in Aurelia. I don't want to derail this thread, but I've been doing some tests with Voiceover and it seems that there are some issues with everything being so dynamic. That said, I've been planning to add some more accessibility issues for this plugin.

**Comment by rquast** [comment]
Here's a non-native scrollbar example I found which looks pretty similar to what exists already in the code. https://codemirror.net/demo/simplescrollbars.html .. they just use mousedown, mousemove and mouseup events on the scroll div element. I think it would be pretty simple to make the existing scroll do the same thing by adding those extra events to the scrollhandler. https://codemirror.net/addon/scroll/simplescrollbars.js

**Comment by martingust** [comment]
More discussion on this https://github.com/aurelia/ui-virtualization/issues/23
