### ISSUE TITLE
Rendering issues when scrolled to the bottom and array mutates

### ISSUE THREAD

**Issue by rowellx68** [aurelia/ui-virtualization#146]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.4

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.11.1

* **NPM Version:**
6.8.0

* **JSPM OR Webpack AND Version**
webpack-cli 3.2.3

* **Browser:**
Chrome 72 | IE 11 | Edge 42

* **Language:**
TypeScript 3.1.2

**Current behavior:**
When the table is scrolled right to the bottom and the array is mutated, it renders empty rows after the actual elements. This only happens when it is scrolled right to the bottom.

Sample application demonstrating the bug can be seen here https://github.com/rowellx68/virtual-repeat-sort-issue

![render-issue](https://user-images.githubusercontent.com/10155704/53003043-fc218400-3425-11e9-9c99-be692a05ae69.gif)

**Expected/desired behavior:**

* **What is the expected behavior?**
Expected behaviour is for the rows to render correctly and preserving the scroll position when the array mutates.

**Comment by bigopon** [comment]
Thanks for filing this, I'll have a look into it soon
