### ISSUE TITLE
Repeater breaks on collection change - parent.removeChild(bottomBuffer) error

### ISSUE THREAD

**Issue by vermilion** [aurelia/ui-virtualization#156]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.7

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
11.10.0

* **NPM Version:**
6.9.0

* **Browser:**
all

* **Language:**
TypeScript 3.4

**Current behavior:**
When data in underlined collection changes and new collection is empty repeater breaks with error
![image](https://user-images.githubusercontent.com/2167823/57998741-6c9a7880-7adb-11e9-91ab-9e9cbe70511e.png)

As a temp workaround i added a check but the Buffer still exists in DOM
```js
if(parent.contains(bottomBuffer))
	parent.removeChild(bottomBuffer);
```

**Expected/desired behavior:**

Cannot repro in gist :(

* **What is the expected behavior?**
No error on change

**Comment by bigopon** [comment]
@vermilion can you help paste some relevant html?

**Comment by vermilion** [comment]
Solved. Fixed the **if.bind** clauses in my markup and the problem gone
```html
<table>
     <tbody>
        <tr if.bind="rows.length === 0"></tr>
        <tr if.bind="rows.length > 0" virtual-repeat.for="$row of rows">
            <td>content</td>
        </tr>
     </tbody>
</table>
```
