### ISSUE TITLE
Lifecycle methods not triggered

### ISSUE THREAD

**Issue by Mobe91** [aurelia/ui-virtualization#169]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.7

**Current behavior:**

The caveats section states:
```
virtualization requires appropriate removing and inserting visible items, corresponding lifecycle of items view will also be triggered while inserting (bind, attached) or removing (unbind, detached)
```

Maybe I am misunderstanding this statement. Consider the following virtual repeat:
```html
<div virtual-repeat.for="item of items" infinite-scroll-next="getMore">
  <my-item-view item.bind="item"></my-item-view>
</div>
```
I would expect the lifecycle methods on the controller for `my-item-view` to be invoked whenever new items are added/removed from the virtual repeat when the user scrolls. But this is not the case. The item controller lifecycle methods are only invoked a couple of times when the page is initially rendered.

**Expected/desired behavior:**

The lifecycle methods `bind()`, `attached()` / `unbind()`, `detached()` are invoked on the `my-item-view` controller when items are added / removed from the virtual repeat.

**Comment by bigopon** [comment]
@Mobe91 yes you are right. Sorry for the confusion. Moving items ui (views) around will only rebind them without triggering lifecycle all the times.

I'll fix that doc. Does that behavior block you in any way?

**Comment by Mobe91** [comment]
> I'll fix that doc. Does that behavior block you in any way?

Perfect, thank you. Well, I was able to solve my use case by reacting on item changes via `itemChanged` inside my custom element's controller so no, this does not block me at the moment.
