### ISSUE TITLE
Programmatically scroll to item

### ISSUE THREAD

**Issue by michaelbull** [aurelia/ui-virtualization#170]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.7

**Expected/desired behavior:**

I currently have a list of elements that represents an email inbox, where each item is an email in a panel with virtualised scrolling. I'd like to be able to 'jump' the scrollbar to the currently selected item when the user opens an email via a notification (i.e. opens an item that is shown in the inbox by a method that isn't simply scrolling to the item in the list).

In a non-virtualised list I could use [Element.scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView), however with a virtualised list there's of course no guarantee that the item is in the DOM at this point.

Can something be exposed (perhaps a bindable callback?) that would allow me to force the virtualiser to recalculate its current position around a desired 'index' of the list? It doesn't need to be fancy and animated, just an instant jump. Thanks.

**Comment by bigopon** [comment]
@michaelbull does this example work for you https://codesandbox.io/s/httpsgithubcomaureliaui-virtualizationissues170-x5s3c

**Comment by michaelbull** [comment]
That example works, but it doesn't work in my application. Admittedly I am using a `div` for the container and `a` tags for the repeated elements, however when I use the same approach the top/bottom "spacer" elements that the plugin inserts don't have their height recalculated appropriately when changing the container's `scrollTop`. I don't know why your example causes it to properly refresh and recalculate the size of the buffers and mine doesn't.

**Comment by michaelbull** [comment]
Ok, I have a workaround which involves manually dispatching the event to trigger the refresh:

```typescript
items.scrollTop = index * itemHeight;
items.dispatchEvent(new Event(VirtualizationEvents.itemSizeChange));
```

This seems to work perfectly, thanks for your help @bigopon.
