### ISSUE TITLE
virtual-repeat doesn't work for containerless custom components

### ISSUE THREAD

**Issue by palktonderAtpowelno** [aurelia/ui-virtualization#171]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.7

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.12.0

* **NPM Version:**
6.9.0

* **JSPM OR Webpack AND Version**
webpack 4.41.2

* **Browser:**
all

* **Language:**
ESNext at least (maybe all)

**Current behavior:**
I create a custom component for the items in a list. Because the child selector (>) is used in CSS I have no control over, I have to make the custom control containerless. While this works for a normal repeat, it fails with virtual-repeat. The problem is that the code tries to call element.getBoundingClientRect on an object that is not a DOM element. As this fails, only the first item is the list is shown

**Expected/desired behavior:**

I'm not able to recreate it in Gist, but I have a codesandbox: https://codesandbox.io/s/aurelia-ui-virtualization-template-7igvk?fontsize=14, that shows the current behavior

* **What is the expected behavior?**
The virtual-repeat should work as the standard repeat in that all the items should be visible

**Comment by bigopon** [comment]
@palktonderAtpowelno 
As you noticed, it fails on a containerless element, it's intentional since a containerless custom element usually results in very difficult to calculate height. It's specifically stated in the readme for that reason.
For your case, you can simply use `as-element` instead:
![image](https://user-images.githubusercontent.com/9994529/68109988-0b0e7f00-ff40-11e9-9289-9020c7c18d5e.png)

updated sandbox https://codesandbox.io/s/aurelia-ui-virtualization-template-qkv0j

**Comment by palktonderAtpowelno** [comment]
Unfortunately, this doesn't fix any problem, rather it broke the standard repeat version. Whether you use the actual custom control directly or through as-element, the css still gets screwed up because of the intermediate element which I try to avoid using containerless. BTW, is it caveat no. 1 that explains this problem? Not being intimately familiar with the inner workings of Aurelia, it's a bit hard to connect those dots :-), that is, to understand that caveat no. 1 actually describes my problem. If it does, and this is an unsolvable problem, maybe it could be stated more clearly/explained in more detail (containerless custom element could be an example of this problem).

**Comment by bigopon** [comment]
@palktonderAtpowelno which is the intermediate element in the example? It should be all eliminated in my example, as you can see in `list-demo.html`

**Comment by palktonderAtpowelno** [comment]
You are right, the reason the css came out wrong was because some css classes on the ul element hadn't been included (now added through as-element="contact-list". That said, the list won't scroll beyond the first 20 items. Is there a reason for this?

**Comment by bigopon** [comment]
@palktonderAtpowelno I think probably you are using an older version of this plugin in the sandbox. Try upgrade it to beta-7 maybe? You can see it here https://codesandbox.io/s/aurelia-ui-virtualization-template-qkv0j

**Comment by palktonderAtpowelno** [comment]
I used the as-element approach in my local solution, with the aurelia-ui-virtualization@1.0.0-beta.7 installed, and while the visual presentation was correct, it showed the same behavior of only presenting a subset of the elements. It seems to be the first "page" of elements (24 elements for the full screen, fewer when the browser size is reduced).

**Comment by bigopon** [comment]
@palktonderAtpowelno can you try setup some height for the list container and see if its working? Else can you give a bit more instruction how i can replicate the issue?

**Comment by palktonderAtpowelno** [comment]
I have to look more into it. I've just found it works in one part of the app and not another. Very strange

**Comment by bigopon** [comment]
@palktonderAtpowelno please open new issue if you still experience any issues. Thanks for creating this
