### ISSUE TITLE
Virtual repeater goes into infinite loop

### ISSUE THREAD

**Issue by FreddyMcRay** [aurelia/ui-virtualization#198]
**I'm submitting a bug report**

* **Library Version:**
I used demo-app from your repo

* **Operating System:**
Windows 10

* **Node Version:**
10.19.0

* **NPM Version:**
6.13.4

* **JSPM OR Webpack AND Version**
webpack 4.28.4

* **Browser:**
Chrome 86

* **Language:**
TypeScript 2.9.2

**Current behavior:**
The trick is to combine virtualized repeater and sort value converter.
If I remove elements one by one from the array (repeater watches this array) and finally remove the last one, virtualized repeater  will go to infinite loop.

**Expected/desired behavior:**
Virtualized repeater should not go into infinite loop. At least simple repeater doesn't.

Pls use this demo-app to repro https://github.com/FreddyMcRay/ui-virtualization/tree/repro/sample/demo-app

steps:
1. start the app
2. click on "Remove 1 at top" button several times to delete all elements from the list
3. done, application is frozen

* **What is the expected behavior?**
The app should work normally

* **What is the motivation / use case for changing the behavior?**
The app becomes unusable. + behavior differs from the way how simple repeater works

**Comment by bigopon** [comment]
Following the step described, I couldn't reproduce the bug. Can you help with some reproducible demo? You can base on this link https://codesandbox.io/s/m781l8oyqj?file=/index.html

**Comment by FreddyMcRay** [comment]
I can't run demo app in the sandbox. It tells me that aurelia-ui-virtualization module could not be found.
https://codesandbox.io/s/bitter-voice-sovoh

So you ran build command, started dist/index.html, removed all elements and it didn't help to repro?
I can record a video if you wish.

**Comment by FreddyMcRay** [comment]
Hi All! Any updates?

**Comment by bigopon** [comment]
@FreddyMcRay are you able to work around this issue for now? I think it can be done via:
```ts
this.array = this.array.slice().sort()
```
> I can't run demo app in the sandbox. It tells me that aurelia-ui-virtualization module could not be found.

I'm not sure why it didn't work for you, I just updated that sandbox, can you try again?

**Comment by FreddyMcRay** [comment]
Sorry for delayed answer
To solve this I added additional check to not sort empty array

> I'm not sure why it didn't work for you, I just updated that sandbox, can you try again?

![image](https://user-images.githubusercontent.com/26858004/98656934-524cfe00-2352-11eb-8873-527760b47644.png)

**Comment by blarsern** [comment]
I have similar behavior with sorting and repeater.

Just upgraded to the latest version from  1.0.0-beta.3.3.2 which worked just fine.

This causes the browser to hang completely, dead, needs to be killed:
virtual-repeat.for="r of visibleResult | sort:sort:sortDir"

This loads fine:
virtual-repeat.for="r of visibleResult"

So any tips ?
