### ISSUE TITLE
Dimensions for scroll, etc calculated once on attached(). Needs to be dynamic.

### ISSUE THREAD

**Issue by rquast** [aurelia/ui-virtualization#21]
itemHeight, virtualScrollHeight, etc are all calculated from the size of the scroll view when attached() is called in virtual-repeat.js. There are a few problems with this:
1. It doesn't resize.
2. If the element is hidden (display none), then this.virtualScrollHeight remains as -2.

Needs to be a hook for resize and display to recalculate these values.

**Comment by martingust** [comment]
@rquast Agree. Ultimately if it could dynamically calculate the itemHeight while scrolling to allow for different item heights throughout the list.

**Comment by vegarringdal** [comment]
Question is there a event listener I can hook up to listen for when client Height/client Width changes without using setTimeout and check?
Having the same issue with my grid element, have workaround with a function that can be called for it to fix it self that can be used with dialogs or similar using display:none
But would really like to improve this part

**Comment by Alexander-Taran** [comment]
Stale from 2016

**Comment by bigopon** [comment]
Similar to #69

We should probably use ResizeObserver

CanIUse https://caniuse.com/#feat=resizeobserver
Article https://developers.google.com/web/updates/2016/10/resizeobserver
Polyfill https://github.com/que-etc/resize-observer-polyfill

@EisenbergEffect @AStoker @Alexander-Taran Should we auto detect ResizeObserver support and automatically observer & react to size change?
