### ISSUE TITLE
access to parent binding context not working

### ISSUE THREAD

**Issue by reinholdk** [aurelia/ui-virtualization#22]
Hi,

looks like virtual repeat no longer supports access to $parent.
Probably needs to be adapted to the new overrideContext concept in pre beta release.

Regards
-- Reinhold

**Comment by martingust** [comment]
Will take a look at this before beta release next week.

**Comment by martingust** [comment]
Thanks, fixed in https://github.com/aurelia/ui-virtualization/commit/0e0f3e65529d455544f820e96e940bf084c8ce84
