### ISSUE TITLE
Page Up, Page Down, and Scrollbar dont' work

### ISSUE THREAD

**Issue by ghost** [aurelia/ui-virtualization#25]
Hi,

I ran the demo, bu the Page Up, Page Down, and Scrollbar do not work.  Are these features on the roadmap?

Very nice work, thank you,

Karl

**Comment by martingust** [comment]
@kdawg1406 Definitely on the roadmap. Thanks for reporting.

**Comment by martingust** [comment]
Fixed in https://github.com/aurelia/ui-virtualization/commit/dc486a9ee43d7f7e4893f688d8be2b56b5910b4c
