### ISSUE TITLE
can we replace with third party scroller like iscroll

### ISSUE THREAD

**Issue by samlin99** [aurelia/ui-virtualization#26]
Hi there,

Is it any plan to use other scroller plugin like iscroll instead of default scrolling feature? 

Thanks,
Sam

**Comment by martingust** [comment]
Hi Sam, 

No plans for that at the moment. Right now we are experimenting with an implementation leveraging the browsers native scroll in this branch https://github.com/aurelia/ui-virtualization/tree/native-scrolling. Would love to get your feedback on that. Maybe both aproaches could be supported later on.

**Comment by samlin99** [comment]
@martingust 
Per my previous request, that I will need similar touch scrolling behavior in mouse environment. Your master code which is easier for me to fix. here is my commits (https://github.com/samlin99/ui-virtualization/commits/master). Do you think that will be something we can add into branch code to have this flexibility?

**Comment by martingust** [comment]
@samlin99 Do you want to have momentum scroll when scrolling with the mouse wheel? In the `native-scrolling` branch the `ScrollHandler` class will go away, and the browser will handle all scrolling. Should make the maintenance a lot easier and will give users the expected experience across browsers, platforms and scroll inputs. 

Feel free to pull down the branch and start the sample app with `gulp watch` and see how it works with your requirements. Note it's still in WIP, you will probably run into some bugs, but hopefully you'll get the idea.

**Comment by martingust** [comment]
Closing this since there are currently no plans to integrate this with `iscroll`.
