### ISSUE TITLE
Support Inline UI Virtualization (No Need for Fixed-Height on Container)

### ISSUE THREAD

**Issue by YipYipX4** [aurelia/ui-virtualization#29]
Hi, 

If you already know a fixed height for your items, and you also know how many items that you have, then it is possible to virtualize the UI without requiring the end developer to put a fixed height on the container.  You can have the plug-in set the total height of the container based on itemHeight \* itemCount, and then you can rely on the main scroll bar of the page to scroll through your giant list and you can render only the items that would be in view by putting an enormous margin-top on the first visible item (in order to skip over all the non-visible items above) and render only enough items to fill up the view port (and skip non-visible items below).

For example:
If you are rendering 1,000 items that are each 100 pixels tall, then you'd set the height of the container to 100,000 pixels.  Then, when the page has been scrolled down so that the top of the view port is 50,000 pixels down, you would render item 500 with a margin-top of 50,000 and then render enough additional items to fill up the view port. (You can adjust this a bit to have a buffer above and below in order to make it smoother, hopefully rendering items before they even come into view.)

This would allow having multiple virtual repeaters in a very tall page. If you scroll all the way past the first repeater, then none of its items would be displayed.

FYI, I have successfully been able to render multiple large spreadsheets (some with over 10,000 rows) in a page using the handsontable control, which uses this technique.

**Comment by martingust** [comment]
@YipYipX4 I have been thinking about this as well, this is definitely something we want to look into and would love to support. Thanks for the ideas!

**Comment by jwahyoung** [comment]
A quick note - awesome idea, but if we implement this we'll need to think about accessibility (for people who either don't use a mouse, or don't scroll at all - such as people with screen readers and such).

**Comment by YipYipX4** [comment]
@jedd-ahyoung Yes, I agree that accessibility is a concern, but I think that is true for any virtual or dynamic UI whether it is inline or not, right?  I usually like to avoid having more than one scrollbar.  The demo avoids this by fitting the virtualized container into the main viewport, eliminating the main scrollbar, but sometimes we may want to put a virtualized repeater in an already scrollable page without having a nested scrollbar.

BTW, another scenario to consider is printing.

**Comment by jwahyoung** [comment]
Currently, the ui-virtualization plugin should work within any container -
and it should support multiple containers at the same time. (There was a
pull request for this a while back, I believe.) What you're proposing seems
more like an optimization at this point. A very good one, no doubt.

From what I can tell, the current behavior will remove elements if they are
scrolled beyond the current viewport. This means that if the viewport
itself is scrolled out of view, the elements in that viewport will still
persist. Your solution would remove those elements from the viewport if the
viewport itself is scrolled out of the window area. Is this correct, or did
I misunderstand?

2016-02-13 8:32 GMT-05:00 YipYipX4 notifications@github.com:

**Comment by YipYipX4** [comment]
It is not just about removing elements from containers that are off-screen.  That would simply be a small optimization.  This is about not requiring a fixed height on the container.  My understanding is that if you don't specify a fixed height on your container, then all elements will be rendered, effectively disabling UI virtualization (in that case, the solution I'm relaying would be a very significant optimization!).

FYI, this isn't my idea.  I mentioned the HandsOnTable open source / freemium spreadsheet control that uses this technique, and don't believe it is a new thing. 

Here's a demo I put together using the HandsOnTable control:
https://plnkr.co/edit/0w9SFmwueq7xJK4lLiIk?p=preview

There are 2 spreadsheets with 1000 rows each.  
- FYI, notice that each header row is "sticky" and will persist as you scroll the top of the spreadsheet out of view (but will disappear when the entire spreadsheet is out of view).  (This is a fantastic usability improvement, just FYI.)
- There is only one scrollbar.
- You can "inspect element" on a cell and you will see that there are only enough TR elements to fit the screen with some buffer above and below.
- If, using Chrome, you open the preview in a separate window and press Ctrl+P, you'll see in the print preview that space is reserved for the height of both spreadsheets (about 25 pages each), but only the first few rows of each spreadsheet show up (ideally virtualization can be disabled automatically when printing).  In contrast, when you try to print the Aurelia UI Virtualization Demo, you will get one page and a scrollbar will be printed (this might actually be easier to fix because you could use a stylesheet rule to remove the container's fixed height when printing).

**Comment by jwahyoung** [comment]
Oh, wow! I see, and I am incredibly impressed. If this solution can also
work inside of a fixed-height container (with overflow auto or something)
then I'm all in. In fact, I have a personal application that could
definitely benefit from this type of behavior. Thank you for clarifying -
the demo made all the difference.

2016-02-13 20:33 GMT-05:00 YipYipX4 notifications@github.com:

**Comment by Wyzix33** [comment]
Hi, here is another approach, maybe it can help you, it works with variable row height, there is still a browser limit to container height, but it's not that important

https://rawgit.com/Polymer/labs/master/list/virtual-scroll-examples.html

set the item complexity to complex and hit reset, try it on, it has a few options 
virtualList.pageSize = 10;
virtualList.numPages = 2;
virtualList.numInitialPages = 200;
you can play with :) I use it on a production app and it works with 400k+ rows and virtualList.numInitialPages = 4. 

Hope it helps.

**Comment by martingust** [comment]
I think this can be achived by adding a new viewStrategy that uses window as container, the viewStrategy interface might need some modifications to calculate the position of the list and probably something else too. Will look into this next after getting the change handeling right and probably also infinite scroll support.

**Comment by martingust** [comment]
@YipYipX4 Work on this started over here https://github.com/aurelia/ui-virtualization/pull/38

**Comment by martingust** [comment]
This is now implemented in master.
