### ISSUE TITLE
jspm install name issue

### ISSUE THREAD

**Issue by rquast** [aurelia/ui-virtualization#3]
If you do a jspm install github:aurelia/ui-virtualization , the config will map aurelia/ui-virtualization and not aurelia-ui-virtualization. Currently need to manually go into config.js and fix. Should be mapping the name correctly (following the convention of other Aurelia modules).

**Comment by martingust** [comment]
@rquast I created a PR to the JSPM registry to add aurelia-ui-virtualization: https://github.com/jspm/registry/pull/474. 

Before this is merged you can jspm install be specifying the name: `jspm install aurelia-ui-virtualization=github:aurelia/ui-virtualization`

Also updated the readme file.

Thanks

**Comment by rquast** [comment]
Great! Thank you.
