### ISSUE TITLE
Suggestion for demo

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/ui-virtualization#31]
When I add 10 000 rows 5 times then it would have been nicer if the id was 1-50 000, not 0 to 10 000 5 times.
Also a counter on how many rows the list have would also be nice.

**Other:**
Did not want to start new thread since its beta and do not know if its updated to latest source, but incase they are unknown Ill write them down.
So feel free to remove this if you want.

Here is what I noticed when I tried the demo beta.
- After 200 k rows the li-e between records goes away.
- with list of 200k dragging scrolltumb from top to bottom is really sluggish/laggy (on virtual pc so this might be my end)
- toggle visibility button breaks grid
- if I scroll to bottom when demo is loaded, hit "remove at bottom" about 6 times, the grid acts unnormal/bugs
- when page loaded and I start hitting remove at top for 100 times the grid bugs out and show no 99 on each row

**Comment by martingust** [comment]
Will fix those demo issue with next update. The plugin is actually only in alpha, the plan is to build a more sophisticated demo for beta/v1 release, current is more of a dev/testing sample.

**Comment by martingust** [comment]
As for the other issues:
- What browser you in? I just tested with 200k items, it loaded in 4 sec and I could drag the scrollbar pretty quickly through all of the items, this is in Chrome on Mac Book Pro. 
- Toggle visibility should be fixed in master.
- I can replicate the last two bullets, they are related. I see where the issue is, will look into a way to fix that.

Thanks!

**Comment by vegarringdal** [comment]
I tested just now again in chrome, windows 64,
Click 20 times on add 10 000 button, then started dragging scrollbar from top to bottom, then back again, and it is kinda laggy.
But do you really wanto try and render that kinda dragging at all, why not stop rendering for about 200 ms after user stops that kind of scrolling.
if you are getting data from serverside and list contains 1 million rows it will try and ask for data like crazy.
But can test again on my home computer later, the one Im on now is kinda slow :-)

**Comment by vegarringdal** [comment]
I tried again, feels laggy when there is a lot, when I drag up and down the scroll bar
But again, this isnt what a person usually does, so maybe it does not really mater.
Tell me when you have updated code for demo and I can help you test for bugs if you want.
Would have been great if there was a button for adding 100 000 rows too :-)

**Comment by martingust** [comment]
@vegarringdal Definitely think that is a common thing to do, where the experience should be as good as possible. Would you mind creating a separate issue for that.

**Comment by vegarringdal** [comment]
Yep
Here:
https://github.com/aurelia/ui-virtualization/issues/33

**Comment by martingust** [comment]
@vegarringdal  Please feel free sending PR with enhancements and bug fixes for the sample app in the project. That would be very helpful.

**Comment by vegarringdal** [comment]
I will try, but need to learn Aurelia better.
Ill start and see if I manage to make a better demo for my grid that I want to make into a plugin in the end, just need to add drag-drop headers, re-size headers and click on headers to sort.
Then I'll might get a few ideas and learn from some mistakes first. :smile:

On the bright side, Aurelia is so fun to use and learn, that I might be able to make something that actually works :joy:
