### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/ui-virtualization#32]
Hi guys,

I have my application running. So as soon as I installed that plugin the with JSPM I see an error:

TypeError: Aurelia is not a function
    at http://localhost:9000/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.0.1/aurelia-bootstrapper.js:96:21
    at h (http://localhost:9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66)
    at http://localhost:9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
    at MutationObserver.e (http://localhost:9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1958:55)

Do you know why that could happen?

Regards

**Comment by martingust** [comment]
Do you have any forks? `jspm inspect --forks`

**Comment by martingust** [comment]
@hmarcelodn Do you still have installation issues? Please try the latest release.

**Comment by martingust** [comment]
Another release is out, closing this.
