### ISSUE TITLE
Large list 200k+ is lags when dragging up and down and up and down fast.

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/ui-virtualization#33]
Large list 200k+ is lags when dragging up and down and up and down fast.

Click 20 times on add "10 000" button, and give it a while to finish.
Drag scrollbar tumb/handle up and down and up and down and you will se that it lags.

One solution could be to not update view when scrolling like that, and update it after user stops.
Grid should at least not try and request any data from server automatically when doing so.
My opinion...

**Comment by vegarringdal** [comment]
Hi
This is what I was trying explain when dragging up and down:
Open page, and click 10-20 times on add 10000 button. (then giv it a few sec while it loads, some bad coding here, not very async)
If you drag up and down it the scrollbar tumb it will stay smooth nomather how many becouse if scroll is very large it does not update view
Sample:
http://vegarringdal.github.io/aureliaGrid/

**Comment by martingust** [comment]
Thanks for the example. I think this need all depends on the requirements. The scrolling is completely smooth when dragging the scrollbar but at the same time the list is completely blank and you might have hard time to know where in the list you are. Same is for momentum scroll, on touchpad or mobile device, the list goes blank which I think should be avoided for as long as possible. Perhaps it could be an optional setting to skip render items when dragging the scrollbar. What do you think?

**Comment by vegarringdal** [comment]
"only when dragging scrolbar" would be best. (but how can you know this during scrolling)?
One thing could be to have something in footer/toast or something showing you what range you are at, like "1000-2000" then it switch to "2000-3000" etc.

Btw, I havent tested my grid much on on touchpad/mobile devices/safari , so I prb have room for improvments in my grid here, was made for desktop, thats why Ive added the sortable%resizable headers, multiselect.
What browser did you use/mobile device, want to improve things that can be better so I can use it for cases where I need a desktop grid.

**Comment by martingust** [comment]
Not sure if displaying the list index you are at will help that much, that will only give you an idea of how much you have scrolled, which you can probably get from looking at the scrollbar itself. Often (I think) the user want to be able to look at the data in the list to be able to quickly scroll to the right position, like when scrolling through an alphabetical ordered list.

This was Chrome on OS X when using the touchpad.

**Comment by vegarringdal** [comment]
When I think about it people usually do more filters if they have a list more than a 1000 :-)
But I  agree its very usefull to see while you scroll and it not going blank, Ill try and implement that into mine as a option too, had bad experience with that and IE09 before, but my code was even a more mess last time I tried it :-)

Added the row/index part here, isnt the most usefull information, hehe
http://vegarringdal.github.io/aureliaGrid/00beta02/

**Comment by martingust** [comment]
@vegarringdal Fix should be in. Number of views that will be moved is now limited to `number of rendered views * 2`. It seems to make it a lot smoother when quickly dragging the scrollbar through 100s of thousand items. 

Thanks for bringing this up, big improvement with little effort!

**Comment by vegarringdal** [comment]
Nice
Will you update the demo with the with the other buttons I told you about at gitter?
Maybe a note about browser limit maximum element height should be on the readme, so people dont think its actually a bug...

**Comment by martingust** [comment]
Good points. Feel free to make a contribution with that :)

**Comment by vegarringdal** [comment]
Ill try, busy with debugging/improving preformance at my grid atm :-)
