### ISSUE TITLE
Infinite pannable workspace

### ISSUE THREAD

**Issue by PieterSmit** [aurelia/ui-virtualization#37]
We are building a diagram workspace and looking for an infinite pannable and zoomable workspace that contains custom elements. (We cannot use canvas, elements can be moved and sized)
Would an extension on this project be a good tool?

**Comment by martingust** [comment]
Do you have any example to show how it is supposed to work? One contraint on the `virtual-repeat` is that each row needs to be equaly tall. We are going to look into a way to allow dynamics height but not there yet.
