### ISSUE TITLE
Setup Instructions in READMEOut of Date

### ISSUE THREAD

**Issue by FunkMonkey33** [aurelia/ui-virtualization#40]
Doesn't seem to work with the 3/29/2016 Aurelia release.

**Comment by martingust** [comment]
They should be updated. What is not working?

**Comment by FunkMonkey33** [comment]
Well I got an error when adding .plugin('aurelia-ui-virtualization') to the configure method.

**Comment by martingust** [comment]
What is the error? Do you have latest of all Aurelia libraries?

**Comment by FunkMonkey33** [comment]
I think so.  I did a fresh npm and jspm install.  
I'll try again later today.  I backed out my changes and am knee-deep in something else.  As soon as I can commit that, I'll try again.

**Comment by FunkMonkey33** [comment]
Well this is embarrassing. It's working fine.

**Comment by FunkMonkey33** [comment]
At least the setup is working.  I'm getting an error saying that it can't calculate item height.  That could be because of a <compose> element that's in there, even though the view inside of the compose has a set height.  I'll play around with it.  Thanks for your help.

**Comment by martingust** [comment]
Awesome! Let me know if you run into any further issues.

**Comment by FunkMonkey33** [comment]
One other question, probably my error, and not worth starting an issue for.  Can you meet me over on Gitter?
