### ISSUE TITLE
Bug when virtual list items are reduced to less than the visible count

### ISSUE THREAD

**Issue by palktonderAtpowelno** [aurelia/ui-virtualization#41]
When I filter the list used in virtual-repeat.for so that the new list is shorter than the count of visible items the old items appear as "ghosts". I think the culprit is in _inPlaceProcessItems of array-virtual-repeat-strategy.js where there is no check in the first for loop whether we are working beyond the itemsLength

```
  if (view.bindingContext[local] === items[i + first] && view.overrideContext.$middle === middle && view.overrideContext.$last === last) {
```

Here items[i+first] can actually point to a non-existing item since the itemsLength is less than viewsLength. In such a case the code should probably remove the old views instead.

**Comment by martingust** [comment]
@palktonderAtpowelno  What version of UI-Virtualization are you running? Related bugs are fixed in latest (0.4.0).

**Comment by palktonderAtpowelno** [comment]
0.4.0. I'm not sure what bug you are referring to, but I'm experiencing these problems with the current source code.

**Comment by martingust** [comment]
Got it reproduced. Will get a fix in soon.

**Comment by martingust** [comment]
@palktonderAtpowelno Patch release with fix is out. Thanks for reporting this!
