### ISSUE TITLE
Virtual-repeat doesn't work with tables

### ISSUE THREAD

**Issue by mikhailshilkov** [aurelia/ui-virtualization#43]
I'm struggling to make Aurelia virtual-repeat.for work with table and tr elements. Here is my markup of the modified Users page of aurelia skeleton app:

```
<table style="width:500px; height: 200px; overflow-y:scroll; display:block">
  <tr virtual-repeat.for="user of users" style="width:500px; height: 50px">
    <td>
      ${user.avatar_url}
    </td>
  </tr>
</table>
```

When I scroll the table down, the items below aren't rendered and I see just the empty space all over. What am I missing?

Update: removing "height: 50px" for tr seems to fix virtualization, although I think it did not help when I tried with my original application.

**Comment by martingust** [comment]
@mikhailshilkov A few fixes are in master, I tested your markup and your issue seems to have been resolved. Will go out in next release. Thanks!

**Comment by mikhailshilkov** [comment]
Works indeed, thank you!
