### ISSUE TITLE
Error when removing a lot it items

### ISSUE THREAD

**Issue by mbernard** [aurelia/ui-virtualization#49]
1. I start with a base array of 5 items
2. Then I add 150 items at index 2 with array.slice
3. Then I remove those 150 items with array.slice
4. I only have 4 items left in my view, however if I check the view model with AureliaContext extension for chrome I see that my array contains 5 items
5. Worst, if I re-do step 2 and 3, I lose items in my view each time. At some point I got this javascript error 

note: I don't have the problem when I add/remove smaller number of items at a time.

![untitled](https://cloud.githubusercontent.com/assets/1928530/14996787/bdce8d76-1149-11e6-9811-b0b9957f91a7.png)

**Comment by martingust** [comment]
@mbernard I found a couple issues when deleting a lot of items, fixes should be in master and hopefully that will also fix your scenario as well. This will go out in next release on Tuesday.

**Comment by mbernard** [comment]
@martingust thx I'll try it out as soon as possible
