### ISSUE TITLE
Doesn't work anymore after update to v.0.4.5

### ISSUE THREAD

**Issue by mbernard** [aurelia/ui-virtualization#51]
Just updated to v0.4.5 and the virtual-repeat.for doesn't work anymore
![image](https://cloud.githubusercontent.com/assets/1928530/15164343/1c3e44c2-16dc-11e6-9707-1a11c4dcdf5f.png)

My UI is super simple
![image](https://cloud.githubusercontent.com/assets/1928530/15164298/f4390cbe-16db-11e6-8d69-d62883340dd5.png)

**Comment by martingust** [comment]
@mbernard Oops, `templating-resources` is missing an export. Will get fix in soon.
