### ISSUE TITLE
Error while calculing item height

### ISSUE THREAD

**Issue by mbernard** [aurelia/ui-virtualization#54]
@martingust 
The virtual-repeat.for doesn't load anymore. It seems that there's always an empty element in the DOM as first child in the repeat and it make the calculateHeight to crash with an error as the height is 0. I don't know why there's always an empty element inserted before the elements that should be renderer. If I use the non virtual repeat.for there's no extra elements. (See screenshot)

Error
![image](https://cloud.githubusercontent.com/assets/1928530/15369256/da85fa46-1cff-11e6-9bd3-3788d8e97a71.png)

HTML template
![image](https://cloud.githubusercontent.com/assets/1928530/15369342/3340be14-1d00-11e6-8be5-da5ca16b1097.png)

DOM with the extra div element inserted by the virtual-repeat.for
![image](https://cloud.githubusercontent.com/assets/1928530/15369382/6a9e7536-1d00-11e6-9427-0b8a50160b79.png)

**Comment by martingust** [comment]
Looks like a problem when iterating to empy array. Will look into this.

**Comment by mbernard** [comment]
@martingust I've tried many things. 
- Empty array
- Array with 1 element
- Array with n elements

In every case I have an empty dom element

**Comment by martingust** [comment]
@mbernard I've just tried installing `virtual-repeat` in a fresh skeleton-navigation and it worked well. Are you up to date with all dependencies and have no forks? Also if possible can you provide some steps on how I can reproduce this, ideally in skeleton navigation.

**Comment by martingust** [comment]
@mbernard Is this still an issue? New release got out yesterday.

**Comment by mbernard** [comment]
@martingust Yes, I'm having trouble reproducing the issue in the skeleton though. I'm workin on it.

I found something that looks like the same error but I'm not sure it is.

If you use a virtual-repeat.for on a `<ul>` with "list-style: none" it seems to cause the same error

**Comment by martingust** [comment]
@mbernard Any update on this? I tested run `UI-Virtualization` [sample](https://github.com/aurelia/ui-virtualization/tree/master/sample) app with `ul` and `list-style: none` and it seemed to work fine.

**Comment by mbernard** [comment]
@martingust I'm sorry, I'm on a super tight schedule for a project and I had no time to dig the issue further. The virtualization was more a nice to have for us, so I put it aside for the time being. I'll try to build you a repro case as soon as I have some free time :D

**Comment by martingust** [comment]
@mbernard I'm sorry you had to put it a side. Please re-open this when you get a repro together and I'll look into your issue. Thanks!
