### ISSUE TITLE
Bug with long arrays, table and mutating the array

### ISSUE THREAD

**Issue by francoishill** [aurelia/ui-virtualization#56]
Suspecting the pending pull-request https://github.com/aurelia/ui-virtualization/pull/50 might solve this bug?

Sometimes when a long array (item height is `32px` and number of items is `> 2000`) is mutated the currently "in view" table rows do not update. When I scroll down the items further down are as expected and when I scroll back up the top ones are correct as well.

By inspecting what happens in code I can see that after sorting the array the `handleCollectionMutated` gets called.

I am running it in Chrome (on Windows) version `50.0.2661.102 m`.

**Comment by martingust** [comment]
Thanks for reporting. Can you please provide some more information on how to reproduce this? Ideally  in a fork of [skeleton-navigation](https://github.com/aurelia/skeleton-navigation/) I can run and see it fail.

**Comment by martingust** [comment]
@francoishill https://github.com/aurelia/ui-virtualization/pull/58 is now merged and might fix your issue, please try next release (Tuesday).

**Comment by martingust** [comment]
@francoishill New release is out, can you check if that solved your issue? Thanks!
