### ISSUE TITLE
Error: Could not calculate item height, when outer element has "display: none;"

### ISSUE THREAD

**Issue by bellstrand** [aurelia/ui-virtualization#63]
When an outer element has the styling: "display: none;" when virtual-repeat.for="" is initialized it can't calculate the item height.

Tested with fresh install of latest skeleton-esnext (using chrome in windows 7).

I'd love to help if anyone can point me in the right direction of where to start.

**Comment by EisenbergEffect** [comment]
I'm not even sure it's possible to fix that. If it has display none...the browser doesn't give it any size.

**Comment by bellstrand** [comment]
Yeah, I know that... but wouldn't it be possible to detect that it doesn't have a size and make the calculations when it gets a size instead? (in my case when i decide to show the element).

**Comment by Thanood** [comment]
Just an idea.. If you use `if.bind` instead of `display: none;` (or `show.bind`) bindings are not evaluated until the `if` condition is true. When that triggers, `virtual-repeat` will be able to calculate a size.

**Comment by bellstrand** [comment]
@Thanood, Thinking about going one of those ways. Currently my element is shown on hover or click of a parent element (which makes this case a bit tricky). Might need to rework that if necessary.

**Comment by martingust** [comment]
One improvement could be to provide an options attribute where you set the item height and the virtual repeat would skip the height calculation when it's attached to the DOM, thoughts?

**Comment by bellstrand** [comment]
@martingust, Does the virtual repeat calculate only on the initial height or does it recalculate if/when the height changes?, if so, would it be possible to manually trigger a recalculate? (and handle the error in a good way?)

**Comment by martingust** [comment]
@bellstrand It does not recalculate when the height changes, it probably could but it will add the complexity keep of adding/removing elements from the view port as the height changes. [Here](https://github.com/aurelia/ui-virtualization/issues/21) is an issue tracking this enhancement.
