### ISSUE TITLE
sample does not work, sample path is missing

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/ui-virtualization#65]
`sample : 'sample',`` is missing in paths.js

https://github.com/aurelia/ui-virtualization/blob/master/build/paths.js#L11-L24

```
var paths = {
  root: appRoot,
  source: appRoot + '**/*.js',
  html: appRoot + '**/*.html',
  style: 'styles/**/*.css',
  output: 'dist/',
  doc:'./doc',
  sample : 'sample',   <----------------this is missing, added this and it works
  e2eSpecsSrc: 'test/e2e/src/*.js',
  e2eSpecsDist: 'test/e2e/dist/',
  packageName: pkg.name,
  useTypeScriptForDTS: false,
  importsToAdd: [],
  sort: true
};


```

**Comment by vegarringdal** [comment]
Would have been nice when running the sample if the ui-virtualization had source-maps too, so you could debug the code.

**Comment by martingust** [comment]
@vegarringdal Thanks for report!

**Comment by vegarringdal** [comment]
Any chance for the source maps too? :smile: 
I dont know much about gulp, it just would be very useful to simply just debug the code, more useful for you if anyone find a bug too.
