### ISSUE TITLE
Recalculate Items Shown on Resize

### ISSUE THREAD

**Issue by AStoker** [aurelia/ui-virtualization#69]
In the event that your scroll container is dynamic in size, and you resize that container to be larger than the initial buffer size, you will notice that you now have a blank space below the items that is not being filled in. When you scroll, you'll see the items being rebound and scrolling appropriately, but the space below remains empty.

**Comment by AStoker** [comment]
Just writing this comment here for either any community member to try, or as a reminder to me :) 
I'm thinking that all we need to do is find a way to determine when the scrolling container has changed size (which might not be too hard to hook into since we are already constantly listening for scroll events via a timeout, we just hook a check for size changes in there too), and then call function used to determine heights (_calcInitialHeights).

**Comment by Alexander-Taran** [comment]
[IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) might be a good candidate to utilize, when the time comes

**Comment by Alexander-Taran** [comment]
linked to this https://github.com/aurelia/ui-virtualization/issues/69

**Comment by bigopon** [comment]
We should probably use `ResizeObserver` 

CanIUse https://caniuse.com/#feat=resizeobserver
Article https://developers.google.com/web/updates/2016/10/resizeobserver
Polyfill https://github.com/que-etc/resize-observer-polyfill

@EisenbergEffect @AStoker @Alexander-Taran Should we auto detect `ResizeObserver` support and automatically observer & react to size change?

**Comment by EisenbergEffect** [comment]
Makes sense to me.
