### ISSUE TITLE
Preserve scroll position

### ISSUE THREAD

**Issue by weoreference** [aurelia/ui-virtualization#7]
Hello,

Suppose I use this feature with a really long list, and then in the middle of the list a user decides to navigate to another route. 

Is there any way to preserve their position on the list when they go back??

Thanks,
Andy : )

**Comment by martingust** [comment]
Good point, that's is definitely something that should be handled.

**Comment by AStoker** [comment]
@weoreference, you should be able to preserve the `scrollTop` position of your element and simply reset that value when you come back. 
I'm going to close this for now, if that solution does not work, please let me know and we can reopen.
