### ISSUE TITLE
Scrollbar doesn't reflect new data

### ISSUE THREAD

**Issue by easyt** [aurelia/ui-virtualization#75]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.1.0.2
- **Operating System:**
  Windows 8.1
- **Node Version:**
  5.5.0
- **NPM Version:**
  3.8.6
- **JSPM OR Webpack AND Version**
  JSPM 0.16.31
- **Browser:**
  Chrome 51.0.2704.106 m
- **Language:**
  ESNext

**Current behavior:**
Virtual Repeat does not seem to readjust its "total virtual" height when navigating to the same route (with a parameter change; i.e. id) where the data in the repeater is reduced (from 1000 items to less than 10). The effect is that the first and last 'li' elements still contain their previous heights (0 and 16596px for the example when going from 1000 items to 10).

**Steps to reproduce:**
1. Create a route with a parameter that will be the number of items to generate for the list.
2. Create markup with a fixed height (300px) ul for the virtual-repeat container.
3. Navigate to the route with 1000.
4. Update the URL to be 10.
5. Take note that the scroll bar still appears the same as it was for the 1000 items.

**What is the expected behavior?**
Th scrollbar should accurately depict the data after it changes do to a navigation to the same route with different parameters.

**What is the motivation / use case for changing the behavior?**
Current software application being developed.

**Comment by martingust** [comment]
@easyt This has nothing to do with the `virtual-repeat` but with the router. I think you will need to clear out the underlying array in the `deactivate` step.
