### ISSUE TITLE
Unhandled rejection Error: Cannot find module './aurelia-ui-virtualization/virtual-repeat-next'.

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/ui-virtualization#76]
Using aurelia navigation skeleton/typescript-webpack, v1.0.0

Installed aurelia-ui-virtualization module v1.0.0-beta.2.0.0 using npm, and I see it in my node_modules directory.

Added the following to my main.js/configure() function:
`.plugin('aurelia-ui-virtualization')`

As soon as this is added, I see the following error in the browser JS console at runtime, running in webpack dev mode:

`Unhandled rejection Error: Cannot find module './aurelia-ui-virtualization/virtual-repeat-next'.
    at webpackContextResolve (http://localhost:9000/app.bundle.js:18341:9)
    at webpackContext (http://localhost:9000/app.bundle.js:18336:29)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15442:48
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9000/aurelia-bootstrap.bundle.js:15441:99)`

I have not added any of the template tags/attributes, and have only added the plugin to the bootstrapping in main.js.  What could be wrong here?

Thanks,
Don

**Comment by Silvenga** [comment]
Had the same issue, I fixed it by following the path here: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/428

They recomeneded to add something like the following to your webpack.config:

```
      includeSubModules: [
        { moduleId: 'aurelia-kendoui-bridge', include: /(autocomplete|combobox|datetimepicker|window)/ }
      ]
```

However, this has been deprecated in favor of resources in the package.json (https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/README.md#resource-and-bundling-configuration). 

So my end package.json looks like:

```
    "aurelia": {
        "build": {
            "resources": [
                "aurelia-ui-virtualization/virtual-repeat-next"
            ]
        }
    },
```

**Comment by martingust** [comment]
@AStoker Any idea about this?

**Comment by AStoker** [comment]
I was not familiar with web pack config needs, and so I'm pretty sure that I need to just add that resource to the line: https://github.com/aurelia/ui-virtualization/blob/master/package.json#L126
Should be a very simple PR. I can include it in the current PR, or make a new one?

**Comment by martingust** [comment]
@AStoker Cool, in current PR is fine, thanks!
