### ISSUE TITLE
Implement scroll from bottom

### ISSUE THREAD

**Issue by rquast** [aurelia/ui-virtualization#77]
Needs a switch where you an make the list scroll from the bottom, instead of from the top. Required for chat window like functionality.

**Comment by stsje** [comment]
I don't think this needs to be part of the plugin. Hopefully it wouldn't be a problem implementing the feature yourself.
Here's an untested example that ideally should scroll to bottom. An improvement would be to scroll to bottom only, if the user haven't already scroll up in the list beforehand.

```
import { TaskQueue, inject } from 'aurelia-framework';

@inject(TaskQueue)
export class Chat {

    constructor(taskQueue) {
        this.taskQueue = taskQueue;
        this.chatMessages = [];
        this.lastFetch = new Date();
    }

    getChatMessages() {
        this.api.getChatMessages({
            since: lastFetch
        })
        .then(response => {
            this.lastFetch = response.timestamp;
            this.chatMessages.push.apply(this.chatMessages, response.messages);
            this.queueScrollToBottom();
        });
    }

    queueScrollToBottom() {
        this.taskQueue.queueMicroTask(() => {
            this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
        });
    }
}
```

**Comment by rquast** [comment]
Thanks very much for this. I did pretty much everything you said there already, except for putting the scrolltop/scrollheight thing inside of the microtask queue. Putting it in there got around the issue (I was previously having to put it in a setTimeout).
