### ISSUE TITLE
aurelia.globalizeResources issue when loading the module

### ISSUE THREAD

**Issue by LivesleyWA** [aurelia/ui-virtualization#8]
The following error message appears when loading the module

_Unhandled promise rejection TypeError: aurelia.globalizeResources is not a function(…)_

 Probably as  a result of Aurelia 0.15.0.

See http://stackoverflow.com/questions/32103562/error-when-loading-aurelia-validation-plugin

After update as proposed in the above, I receive a _Loader must implement loadTemplate_ message.

**Comment by EisenbergEffect** [comment]
@martingust If you have some time, would be great to pick back up work on this library, updating it to the latest bits and seeing if any of the view cache stuff can simplify your implementation. I know there are lots of other features we would like to add, of course. Not sure what your availability is right now. Send me email when you get a chance.

**Comment by martingust** [comment]
Fixed in https://github.com/aurelia/ui-virtualization/commit/0345226744ae2173455951148278e634e4da61c2
