### ISSUE TITLE
[Question] InfiniteScroll vs Virtual-repeat

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/ui-virtualization#85]
Guys,

If i have a 100% table. whats recommended? Infinite scroll? Can i just use virtual-repeat.for and let the framework manage that?

Thanks.

@AStoker

**Comment by hmarcelodn** [comment]
@EisenbergEffect @AStoker  do you guys have any idea on when a final first release would be released? That's a very interesting component.

**Comment by EisenbergEffect** [comment]
We don't have a date. We're trying to work through a few more issues first though.

**Comment by AStoker** [comment]
What do you mean by a 100% table? What is the behavior you're trying to accomplish?

**Comment by hmarcelodn** [comment]
I meant 100% height. 

http://screencast.com/t/ltKCjiwFe2C I tried that.

i.e. I dont need to specify the height, sounds like it manages whats possible.

Thanks.

**Comment by AStoker** [comment]
Right now, there appears to be some strangeness to tables that aren't contained within some scrollable element. I'd recommend placing your table inside a div with a style of `overflow: scroll`on the container div. 

Now, if you're asking about infinite scrolling or virtual repeat, they're both part of the same ui-virtualization plugin, but used for different things, but in conjunction. Virtual repeat out of the box will give you the ability to scroll through a large list of static elements without DOM performance issues. If you're going to be doing some form of paging (where you continually get data from the server), then you use virtual scroll _with_ the infinite scroll callback, allowing you to continually add more data to the list, and _infinitely_ scroll. Make sense?

Side note, screencasts aren't very helpful, especially those of us who shun Flash 😉
I'd recommend just posting your view, and view model code, along with a screen shot.

**Comment by AStoker** [comment]
@hmarcelodn, are you good with this question now, is there anything else I can clarify? Or can we close it?
