### ISSUE TITLE
infinite-scroll-next does not call the method

### ISSUE THREAD

**Issue by NimaAra** [aurelia/ui-virtualization#88]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.3.0.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  4.4.6
  
  
- **NPM Version:**
  3.10.7
  
  
- **Browser:**
  all
- **Language:**
  TypeScript 2.0

**Current behavior:**
Given the view: 

``` html
<div class="row">        
    <p>Rows: ${logs.length}</p>
    <div style="height: 70vh; overflow-y: scroll; overflow-x: hidden; overflow: scroll;">
        <table class="table table-striped">        
            <thead>
                <th>Time</th>
                <th>Instance</th>
                <th>Level</th>
                <th>Message</th>
            </thead>
            <tbody>
                <tr virtual-repeat.for="log of logs" infinite-scroll-next="getMore">
                    <td nowrap>${log.timestampEpoch | dateFormat:'YYYY-MM-DD HH:mm.ss.SSS'}</td>
                    <td>${log.instanceName}</td>
                    <td>${log.level}</td>
                    <td nowrap>${$index} - ${log.message}</td>
                </tr>
            </tbody>
        </table>  
    </div>            
</div>
```

And the view model: 

``` javascript
export class LogDetail {
    private logs: string[] = ['A', 'B']; // some 2000 entries...

    public getMore(topIndex, isAtBottom, isAtTop) {
        console.log(`Top Index: {topIndex} | IsAtBottom: {isAtBottom} | IsAtTop: {isAtTop}`);        
    }
}
```

Even though the initial data is displayed in it's entirety, upon scrolling to the end of the list the `getMore` method is never called. I have also tried the `infinite-scroll-next.call="getMore($scrollContext)"` with the method: `public getMore(scrollContext)` with the same problem.

**Comment by AStoker** [comment]
How many items is your initial page size? What you have seems pretty straight forward...

**Comment by NimaAra** [comment]
I thought so too :-) The `logs` is initialized with 2000 records coming from a web service and all of the rows are displayed correctly. But the `getMore` is never called.

**Comment by AStoker** [comment]
I've noticed a bit of strangeness with tables going on (haven't had the bandwidth yet to tackle it). For kicks and giggles, could you have the exact same code, but change the view so that it uses something else (like a div or a li)? That will just help me isolate the problem, hopefully.

**Comment by NimaAra** [comment]
I just tried the exact same code on a different machine running node _v6.6.0_ and it is performing as expected. weird!

**Comment by AStoker** [comment]
@NimaAra it sounds like you have some setup that isn't behaving correctly. Perhaps the plugin isn't configured correctly in the `main.js`? Did you just copy your entire code base over to another machine and have it work there? Or just the view/viewmodel? If just the view/viewmodel it would seem to me that there is something else going on like either a corrupted package or bad configuration.

**Comment by NimaAra** [comment]
It's all good, I had to clean the _npm cache_ and do an `npm install`. Now everything is fine. I guess there were clashes between packages as my source stayed the same.

**Comment by AStoker** [comment]
Awesome, glad you got it working!
