### ISSUE TITLE
Rebinding List to New Array, List Still Shows Some of the Old Items

### ISSUE THREAD

**Issue by FunkMonkey33** [aurelia/ui-virtualization#89]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.0

* **NPM Version:**
3.10.8

* **JSPM 
JSPM 0.16.45 

* **Browser:**
Chrome

* **Language:**
ES6

**Current behavior:**
When you rebind the virtual list to a new array, 
     e.g. this.myArray = getNewData()
Then the list rebinds, but some of the items from the old array are still present.

* **What is the expected behavior?**
Not that!   List should only contain new items after a rebind.

* **What is the motivation / use case for changing the behavior?**
I'm using the virtual-repeat.for list to display search results.  If they enter a new search, I want the old results to go away, and the new results to display.

**Comment by AStoker** [comment]
Could you set up a basic reproducible gist for us to look at? Definitely seems strange. We're currently replacing our list in a similar manner for searching (although it's a bit different), and we don't have a problem. Might be a specific way you're doing it... But I'm not sure.

**Comment by FunkMonkey33** [comment]
I'll have to do it this weekend.  Thanks for the quick reply!

Aaron

**Comment by FunkMonkey33** [comment]
I will say that we have a bunch of Compose elements in there.  Don't know if that's relevant.  

Thanks again.

Aaron

**Comment by AStoker** [comment]
No problem, I just so happened to have my browser open and saw this issue fly in :)  
Compose elements _might_ be a contributing factor.... But I wouldn't bet on it. I'd really just need to see what's going on to know for sure. I'm usually out over the weekend, so if nobody else gets a chance to look at it, I'll try to take a peek on monday.

**Comment by FunkMonkey33** [comment]
OK, I feel stupid.  How do you add aurelia and this plugin to a gist?  I've never used gist before, just JSFiddle.  Can you point me to a good resource on gist?

Thanks.

**Comment by AStoker** [comment]
Don't feel stupid, sometimes Gist gives me a run for my money too :) If you can't get it to happen in a gist, just make a repository that I can clone and try it on.
A gist example of getting a custom element to work is here: https://gist.github.com/AStoker/3a20dc24ca5c32c4b29fe6990dd30156
I don't have an example with a plugin right now.

**Comment by jdanyow** [comment]
@FunkMonkey33 here's a gist you can use as a starting point: https://gist.run/?id=7542e061bc940cde506b

**Comment by AStoker** [comment]
Related to: #106
Working on resolving there.

**Comment by AStoker** [comment]
Resolved (hopefully) by https://github.com/aurelia/ui-virtualization/pull/107
