### ISSUE TITLE
Dist directory not up to date with source

### ISSUE THREAD

**Issue by jwahyoung** [aurelia/ui-virtualization#9]
This plugin doesn't load, with the following error:

```
aurelia.globalizeResources is not a function
```

The code in the `src` directory is using the correct `globalResources` but the `dist` folder isn't up to date - it looks like the source wasn't built before this was pushed to Github.

**Comment by rquast** [comment]
Oops.. made a dupe issue for this one.

**Comment by martingust** [comment]
Fixed by @jedd-ahyoung PR.
