### ISSUE TITLE
ui-virtualization crash on big array changes

### ISSUE THREAD

**Issue by piwnik** [aurelia/ui-virtualization#97]
Big changes in array cause ui-virtualization crash
```javascript
aurelia-task-queue.js:51 Uncaught TypeError: Cannot read property 'animatableElement' of undefined(…)
getAnimatableElement @ aurelia-templating.js:1507
removeAt @ aurelia-templating.js:1739
removeView @ virtual-repeat.js:605
_removeViewAt @ array-virtual-repeat-strategy.js:213
_runSplices @ array-virtual-repeat-strategy.js:177
_standardProcessInstanceMutated @ array-virtual-repeat-strategy.js:123
instanceMutated @ array-virtual-repeat-strategy.js:104
handleCollectionMutated @ virtual-repeat.js:259
call @ virtual-repeat.js:198
callSubscribers @ aurelia-binding.js:365
call @ aurelia-binding.js:979
flushMicroTaskQueue @ aurelia-task-queue.js:124
(anonymous function) @ aurelia-task-queue.js:68
```

To reproduce make such changes in sample application:
1. In phone-list.html. After "Swap" button add input (line:12)
```html
  <input style="position: fixed" value.bind="value" input.trigger="search()" />
```
2. In phone-list.html. Change source array from "objectArray" to "objectArray3" (line:21) like this: 
```html
  <div virtual-repeat.for="item of objectArray3" class="contact-list-item ${item.name}">
```
3. In phone-list.js. Add implementation of search method, which just replace array content with new items.
```javascript
   
  search () {
    var results = [];

    for (var i= 0; i < this.objectArray.length; i++){
      var item = this.objectArray[i];

      if(item.name.toLowerCase().startsWith(this.value.toLowerCase())) {
        results.push(item);
      }
    }

    this.objectArray3.splice.apply(this.objectArray3, [0, this.objectArray3.length].concat(results));
  }
```
4. In phone-list.js. To the the and of activate method add initial object3Array data
```javascript
   this.objectArray3.splice.apply(this.objectArray3, [0, this.objectArray3.length].concat(results));
```

5. Build, and run application.
In input start typing for first element name. I my case it was "0 Leo Hirthe Sr." so I typed "leo". 
In my case this cause 3 of errors provided earlier.

IN ADDITION if after application load you scroll down and then try type, list will show not existing in source array elements.

NOTE this not happens if you remove items by 1 like in sample application, to reproduce this case you shall add/remove "big" amount of items.

**Comment by EisenbergEffect** [comment]
@martingust @AStoker Can you guys look into this?

**Comment by reinholdk** [comment]
Run into this issue as well. There are other cases where mutations are not handled correctly, e.g. when scrolled down or in case of multiple non-consecutive splices (e.g. when implementing a search/filter for a virtual list). Have provided a PR #101 which to fix those issues.

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust @AStoker Can one of you look at the PR please?

**Comment by avizcaino** [comment]
Hi!, any update on this matter? I'm having similar behavior when updating the lists order after applying some filters...

Thanks!

**Comment by AStoker** [comment]
I've got a few things on my plate at work, but I think I might have enough time to take this. @piwnik or @reinholdk, could one of you guys make a repo or a gist of a minimum project that reproduces this issue? It would just help me get to it faster.

**Comment by reinholdk** [comment]
@AStoker the additional test cases in my PR #101 should be sufficient to reproduce. They are all failing with the current master.

**Comment by wcislom** [comment]
It seems this issue still exists. I have the same problem as guys above. When are you going to fix it? It has taken almost 9 months already.

**Comment by EisenbergEffect** [comment]
@AStoker Can you look into this again?
