### ISSUE TITLE
Data not being bound to DOM when array is changed.

### ISSUE THREAD

**Issue by chuckwatson87-zz** [aurelia/ui-virtualization#98]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.8.1

* **NPM Version:**
3.10.8

* **Browser:**
Chrome 54.0.2840.99  (only one I've tested in so far)
* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
I have an array of around 300 elements.  This array is filtered based on what a user types in a textbox.  If I don't scroll. This seems to work perfectly.  If I scroll about halfway down, and type in the search textbox, it looks like it is bringing back the correct results when I look in the console, but they are not being bound to the DOM properly.  So if it is only supposed to show, say 13, results, I will see 13 list items, on the page, but no data.  

I have created a repository here for the issue: https://github.com/chuckwatson87/au-virtualization-refresh-issues

And here is a GitHub Pages site for it: https://chuckwatson87.github.io/au-virtualization-refresh-issues/index.html.

The easiest way I've been able to recreate this behavior is to is to scroll down about halfway, and type "ann" in the textbox.  

**Expected/desired behavior:**

* **What is the expected behavior?**
For it to return the data with no binding issues

* **What is the motivation / use case for changing the behavior?**
User searching and filtering a big list frequently.

**Comment by EisenbergEffect** [comment]
Ping @martingust @AStoker

**Comment by chuckwatson87-zz** [comment]
FYI, this issue seems similar to the issues that are being addressed with pull requests [99](https://github.com/aurelia/ui-virtualization/pull/99) and [96](https://github.com/aurelia/ui-virtualization/pull/96).  I will re-test once those are merged in.

**Comment by AStoker** [comment]
Related to: https://github.com/aurelia/ui-virtualization/issues/106
Working on resolving there.

**Comment by AStoker** [comment]
Resolved by https://github.com/aurelia/ui-virtualization/pull/107
